#GNUPLOT ANIMATION
unset key
set xlabel "x"
set ylabel "p(x,t)"
set yrange [0:1.0]
#set term postscript eps color enhanced
pause 0.2; plot "wavefuncmain.dat" in 0 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 1 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 2 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 3 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 4 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 5 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 6 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 7 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 8 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 9 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 10 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 11 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 12 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 13 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 14 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 15 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 16 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 17 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 18 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 19 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 20 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 21 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 22 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 23 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 24 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 25 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 26 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 27 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 28 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 29 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 30 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 31 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 32 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 33 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 34 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 35 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 36 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 37 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 38 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 39 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 40 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 41 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 42 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 43 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 44 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 45 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 46 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 47 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 48 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 49 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 50 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 51 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 52 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 53 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 54 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 55 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 56 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 57 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 58 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 59 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 60 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 61 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 62 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 63 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 64 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 65 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 66 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 67 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 68 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 69 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 70 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 71 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 72 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 73 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 74 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 75 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 76 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 77 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 78 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 79 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 80 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 81 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 82 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 83 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 84 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 85 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 86 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 87 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 88 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 89 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 90 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 91 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 92 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 93 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 94 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 95 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 96 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 97 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 98 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 99 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 100 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 101 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 102 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 103 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 104 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 105 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 106 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 107 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 108 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 109 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 110 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 111 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 112 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 113 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 114 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 115 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 116 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 117 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 118 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 119 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 120 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 121 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 122 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 123 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 124 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 125 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 126 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 127 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 128 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 129 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 130 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 131 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 132 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 133 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 134 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 135 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 136 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 137 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 138 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 139 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 140 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 141 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 142 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 143 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 144 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 145 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 146 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 147 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 148 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 149 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 150 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 151 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 152 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 153 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 154 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 155 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 156 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 157 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 158 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 159 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 160 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 161 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 162 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 163 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 164 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 165 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 166 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 167 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 168 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 169 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 170 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 171 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 172 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 173 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 174 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 175 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 176 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 177 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 178 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 179 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 180 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 181 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 182 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 183 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 184 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 185 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 186 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 187 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 188 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 189 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 190 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 191 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 192 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 193 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 194 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 195 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 196 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 197 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 198 with lin lw 3
pause 0.2; plot "wavefuncmain.dat" in 199 with lin lw 3